(ns heuhaufen.mail
  (:require [clojure-mail.core :refer :all]
            [clojure-mail.message :refer (read-message)]))


(defn connect-imap []
  ;; flo the processor ^^ test account with autogenerated PW.
  (def mail-store (store "mail.your-server.de" "flo-der-pro@sesser.at" "IWqD0SdV85Owo8t9"))
  (inbox mail-store)
  )

(defn get-latest []
  (def inbox-messages (connect-imap))
  (read-message (first inbox-messages))
  )

(defn get-all []
  (def inbox-messages (connect-imap))
  (map read-message inbox-messages)
  )

